### ISSUE TITLE
Undefined `ocaml_terminal_get_sigwinch` on macos

### ISSUE THREAD

**Issue by Ngoguey42** [CraigFe/progress#12]
The newest progress version fails at link time with the following error:

```
Undefined symbols for architecture x86_64:
  "_ocaml_terminal_get_sigwinch", referenced from:
      _camlTerminal__entry in terminal.a(terminal.o)
      _camlTerminal__gc_roots in terminal.a(terminal.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by CraigFe** [comment]
Thanks. I suspect the configure step just needs to use the POSIX-compatible bindings on MacOS, but hadn't been able to test it.

By a weird coincidence, I'm currently setting up an M1 Mac, so will fix this shortly!

**Comment by Ngoguey42** [comment]
Note that this occured using an intel macbook pro.
