### ISSUE TITLE
sometimes, people just want the completion percentage to show up

### ISSUE THREAD

**Issue by UnixJunkie** [CraigFe/progress#14]
In the terminal, sometimes you just want some terse feedback.
If this use-case is supported, nice!

**Comment by UnixJunkie** [comment]
Some people will just want the ETA, or both (progress % and ETA).

**Comment by CraigFe** [comment]
I'm not sure if this is intended as a question, but it's indeed possible to get just a completion percentage:

```ocaml
let () =
  let total = 100 in
  Progress.with_reporter (Progress.Line.percentage_of total) @@ fun f ->
  for _ = 1 to total do
    f 1;
    Unix.sleepf 0.025
  done
```

Swapping out `percentage_of` for `eta` yields just the ETA, and `Progress.Line.(list [ percentage_of total; eta total ])` yields both.

**Comment by UnixJunkie** [comment]
Cool, thanks!
