### ISSUE TITLE
Undocumented API breakage from 0.2.2 to 0.3.0

### ISSUE THREAD

**Issue by msprotz** [craigfe/progress#42]
https://github.com/craigfe/progress/commit/029cbc07a5c8def11cba53a3a20dd5954d9928f4 removed the Size module from the .mli of Terminal.

I was previously relying on that functionality to not have to re-implement the terminal width detection logic myself.

Can you either re-instate the Size module within Terminal, or suggest a replacement? Thanks!

**Comment by msprotz** [comment]
I think that'd be great! I don't know how I ended up using this package, perhaps I saw something called terminal on opam written by a trustworthy author and decided it was a fine dependency to take on? ;-)

**Comment by art-w** [comment]
Oups my bad! I'll make a PR shortly with a new `terminal.unix` to re-expose the lost Size functions :)

**Comment by dinosaure** [comment]
@msprotz The last version (0.4.0) fixed your issue (thanks @art-w for your work). You should just put a constraint now and require `terminal.0.4.0`. Can you tell me if it's correct?

**Comment by msprotz** [comment]
It works, thanks!
